### ISSUE TITLE
no tests

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/node_smartystreets#16]

**Comment by dkastner** [comment]
This should definitely have tests. Looks like node has a library, [sepia](https://github.com/linkedin/sepia) very similar to Ruby's VCR, which is great for testing HTTP API clients

**Comment by emk** [comment]
We now have very basic tests for both the CLI and the API. Nothing fancy, and no code paths beyond the default, but we do verify that the default options produce geocoded output.
