### ISSUE TITLE
single-line ("glob") mode breaks

### ISSUE THREAD

**Issue by seamusabshere** [faradayio/node_smartystreets#27]
really you should be able to say

```
--single-line foobar
```

and it will automatically only send the "foobar" column as street - and omit postcode, etc. even if they're provided

**Comment by dkastner** [comment]
The glob mode just flat out breaks now. I was unsuccessful trying to debug this so adding to this issue.

With an input csv:

``` csv
id,glob
1,"123 n blount st # 403, madison, wi 53703"
```

I run: 

```
$ ./node_modules/.bin/smartystreets -i ss.csv --auth-id <secret> --auth-token <secret> --street-col glob --log-interval 1
```

There is no output. I've put in debug statements to show that it tries to pipe each row but I can't figure out at what point it dies/decides to skip.

This is causing failures in rolodeck's tests: https://ci.faraday.io/go/tab/build/detail/rolodeck/31/RunTests/1/BuildAndTest

**Comment by devTristan** [comment]
> I can't figure out at what point it dies/decides to skip.

https://github.com/faradayio/node_smartystreets/blob/master/program.js#L129

**Comment by dkastner** [comment]
I put a debug console.log right after that line and saw it output :(

**Comment by devTristan** [comment]
it would, cb() doesn't stop execution, it just signals to skip the current row (hence `else if`)

**Comment by seamusabshere** [comment]
@devTristan can we get this fixed plz? blocks some Faraday clients

**Comment by seamusabshere** [comment]
@devTristan ping

**Comment by devTristan** [comment]
@seamusabshere does that fix it? Branch is issue-27

**Comment by seamusabshere** [comment]
@devTristan confirmed to work, please merge and re-release

**Comment by devTristan** [comment]
done
